### ISSUE TITLE
404 Not Found when try to download lib from Central or sonatype maven repository

### ISSUE THREAD

**Issue by volpatorafael** [whitfin/siphash-java#1]
Hello!
Would be possible to republish the jar artifacts? These 3 links are returning 404 not found

https://oss.sonatype.org/content/repositories/releases/io/whitfin/siphash/2.0/siphash-2.0.jar
https://repo1.maven.org/maven2/io/whitfin/siphash/2.0/siphash-2.0.jar
https://repo.maven.apache.org/maven2/io/whitfin/siphash/2.0/siphash-2.0.jar

Thanks

**Comment by whitfin** [comment]
Hi @volpatorafael! You should be using 2.0.0, not 2.0. Everything is working as expected :)

**Comment by volpatorafael** [comment]
Thanks a lot @whitfin , it did worked with 2.0.0!

May be it would be good idea to update the Readme file, I copied the reference from there :)
